---
version: "3"

services:
    flask-app:      
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: jakewendling/iss_tracker:midterm
        ports:
            - 5000:5000
